config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost:3000"


  #Routes linked to users
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :follows, except: [:show, :new, :edit, :update]
  end


  #Routes for tags (follows tag)
  resources :tags, except: [:index, :show, :new, :edit, :update]


  #Routes for the pages (home, search, about us, contact us)
  root to: "pages#home"
  get "/search", to: "pages#search", as: "search"
  get "/about-us", to: "pages#aboutus", as: "aboutus"


  #Routes for events (and comments, and participations)
  resources :events, except: [:index] do
    resources :comments, except: [:index, :show, :new, :edit]
    resources :participations, except: [:index, :show, :new, :edit]
  end


  #Routes for chats (and messages)
  resources :chats, except: [:new, :edit, :update, :destroy] do
    resources :messages, only: [:create]
  end


  #Routes for flags
  resources :flags, only: [:new, :create]


  #REST API RESOURCES
  namespace :api, defaults: { format: "json" } do
    resources :users, only: [:index, :show]

    resources :events, except: [:new, :edit] do
      resources :comments, except: [:new, :edit]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  devise :omniauthable, omniauth_providers: %i[facebook]

  # validate username
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  #To allow users to login with username or email
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  # Only allow passwords of 8 characters minumum with lower and upper case letters, numbers and punctuation.
  def password_complexity
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^\w\s])/
    errors.add :password, "Complexity requirement not met. Please use: 1 uppercase, 1 lowercase, 1 digit and 1 special character"
  end

  validate :password_complexity

  # Oauth
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.email.split("@")[0]
      
      require "open-uri"
      # open the link
      downloaded_image = URI.open(auth.info.image)

      # upload via ActiveStorage
      # be careful here! the type may be png or other type!
      user.avatar.attach(io: downloaded_image, filename: "avatar.jpg", content_type: downloaded_image.content_type)

      user.skip_confirmation!
    end
  end

  # User Profile image
  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  def avatar_thumbnail
    begin 
      avatar.variant(resize: "100x100!").processed
    rescue
      ActiveStorage::Blob.create_and_upload!(
        io: File.open(
          Rails.root.join(
            "app", "assets", "images", "default_profile.jpg"
          )
        ),
        filename: "default_profile.jpg",
        content_type: "image/jpg",
      )
    end
  end

  validate :avatar_format
  def avatar_format
    if avatar.attached? && !avatar.content_type.in?(%w(image/jpeg image/png))
      errors.add(:avatar, "Image type is not supported try with jpeg or png")
    end
  end

  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            "app", "assets", "images", "default_profile.jpg"
          )
        ),
        filename: "default_profile.jpg",
        content_type: "image/jpg",
      )
    end
  end

  # followers and following
  def following
    Follow.where(follower: self).length
  end

  def followers
    Follow.where(followed: self).length
  end

  def isFollowing(user)
    !Follow.where(follower: self, followed: user).empty?
  end

  def followsTag?(tag)
    !FollowsTag.where(user: self, tag: tag).empty?
  end

  def verificationAsked?
    !Flag.where(user: self, reason: "Verification").empty?
  end

  def followingTags
    ht = FollowsTag.where(user: self)
    arr = []
    for elem in ht
      arr << Tag.find(elem.tag_id).name
    end
    return arr
  end

  # give api key only after user is verified
  validates_uniqueness_of :secretkey, allow_blank: true

  after_commit :add_secretkey, on: %i[create update]

  def add_secretkey
    if self.verification
      unless !self.secretkey.nil?
        self.secretkey = SecureRandom.urlsafe_base64(30, false)
        self.save
      end
    else
      unless self.secretkey.nil?
        self.secretkey = nil
        self.save
      end
    end
  end

  # Controlla che la position sia una stringa di coordinate valide, come fatto per gli eventi, o una stringa vuota se non ci sono:
  def validPosition
    if !position.match?(/^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/) && !position.match?(/^$/)
      errors.add(:position, "Position is not valid")
    end
  end

  validate :validPosition

  # Funzione chiamata da whenever per il resoconto settimanale
  def self.send_report_email_all
    for user in User.where(mailflag: true)
      ReportMailer.send_report_email(user).deliver
    end
  end

  # dependent destroy for user
  has_many :child_chats1, :class_name => "Chat", :foreign_key => "user1_id", dependent: :destroy
  has_many :child_chats2, :class_name => "Chat", :foreign_key => "user2_id", dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :flags, dependent: :destroy
  has_many :child_flags, :class_name => "Flag", :foreign_key => "flaggedUser_id", dependent: :destroy
  has_many :child_follower, :class_name => "Follow", :foreign_key => "follower_id", dependent: :destroy
  has_many :child_followed, :class_name => "Follow", :foreign_key => "followed_id", dependent: :destroy
  has_many :follows_tags, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :participations, dependent: :destroy

  # Overwrite json for api
  def as_json(options = {})
    super(({ only: %i[id username verification bio] }).merge(options))
  end

  def verificationIcon
    if self.admin?
      "admin-icon"
    elsif self.verification?
      "verified-icon"
    else
      ""
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  #GET su /api/users/ 
  def index
    if params.has_key?(:apiKey) && !getUserBySK(params[:apiKey]).nil?
      @user = User.all
      render json: @user.as_json(methods: %i[following followers followingTags])
    else
      render body: nil, status: 401
    end
  end
 
  #GET su /api/users/:id
  def show
    if params.has_key?(:apiKey) && !getUserBySK(params[:apiKey]).nil?
      if User.exists?(params[:id])
		  @user = User.find(params[:id])
		  events = Event.where(user_id: params[:id])
		  
		  render json: @user.as_json(methods: %i[following followers followingTags]).merge(events: events.as_json)
      else
      	  render body: nil, status: 404
      end
    else
      render body: nil, status: 401
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    id = params[:id]

    if User.exists?(id)
      @user = User.find(id)
      @events = Event.where(user_id: id)

    else
      render_404
    end
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def getFollowingId(follower,followed)
        Follow.where(follower: follower, followed: followed)[0].id
    end
end

app/views/users/show.html.erb
<%= javascript_include_tag "follows" %>
<div class="card">
    <div class="card-body">
        <div class="media">
            <%= image_tag @user.avatar_thumbnail, class:"avatar mr-3" %>
            <div class="media-body">
                <div class="d-flex justify-content-between flex-wrap">
                    <div>
                        <h3 class="mt-0"> <%= @user.username %>
                        <div class="<%= @user.verificationIcon %>" style="vertical-align: middle;"></div>
                        </h3>
                    </div>
                    <% if user_signed_in? && @user != current_user %>
                        <br>
                        <div>

                        <button class="btn btn-danger mr-2" onclick="flag('user','<%= @user.id %>')"> <div class="flag-icon"></div> </button>

                        <%= button_to( chats_path, method: :post, params: { chat: { user_id: @user.id }},
                                    form_class: "d-inline-block", class:"btn btn-success mr-2" ) do %>
                            <div class="chat-icon"> </div>
                        <% end %>
                            <% if ! current_user.isFollowing(@user) %>

                                <%= button_to( user_follows_path(@user), method: :post, 
                                    form_class: "d-inline-block", class:"btn btn-primary" ) do %>
                                     <div class="follow-icon"> </div> Follow 
                                <% end %>
                              
                            <% else %>
                                <%= button_to( user_follow_path(@user,getFollowingId(current_user,@user)), method: :delete, 
                                    form_class: "d-inline-block", class:"btn btn-primary" ) do %>
                                    <div class="unfollow-icon"> </div> Unfollow
                                <% end %>
                            <% end %>
                            </button>

                        </div>
                    <% end %>
                </div>
                <a style="cursor: pointer;" onclick="return openFollowers('<%= user_follows_path(@user) %>','follower');">
                    <strong><%= @user.followers %></strong> followers </a>
                ·
                <a style="cursor: pointer;" onclick="return openFollowers('<%= user_follows_path(@user) %>','following');"> 
                    <strong><%= @user.following %></strong> following  </a> <br>
                <%= @user.bio %>
            </div>
        </div>
    </div>
</div>
<div class="card mt-4">
    <div class="card-body">
        <h3 class="card-title">Events</h3>
        <div class="d-flex flex-wrap flex-md-row flex-column">
        <% @events.each do |event| %>
        <div class="col-md-6 my-3">
            <div class="card card-event hover-info" style="min-height: 270px; height:30vh">
                    <div id="cover" class="cover-bg-blur" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                    <div id="cover-noblur" class="cover-bg" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                <div class="card-body">
                    <%= link_to( event_path(event) ) do %>
                    <%= event.title %>
                    <%end%>
                    <div class="extra-info">
                         <%= event.start.strftime("%e %B %Y, %H:%M") %> - <%= event.end.strftime("%e %B %Y, %H:%M")%> <br>
                         <%= event.where %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
        </div>
        <% if @events.empty? %>
        <span class="text-muted"> This user has no events yet </span>
        <%end%>
    </div>
</div>