config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost:3000"


  #Routes linked to users
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :follows, except: [:show, :new, :edit, :update]
  end


  #Routes for tags (follows tag)
  resources :tags, except: [:index, :show, :new, :edit, :update]


  #Routes for the pages (home, search, about us, contact us)
  root to: "pages#home"
  get "/search", to: "pages#search", as: "search"
  get "/about-us", to: "pages#aboutus", as: "aboutus"


  #Routes for events (and comments, and participations)
  resources :events, except: [:index] do
    resources :comments, except: [:index, :show, :new, :edit]
    resources :participations, except: [:index, :show, :new, :edit]
  end


  #Routes for chats (and messages)
  resources :chats, except: [:new, :edit, :update, :destroy] do
    resources :messages, only: [:create]
  end


  #Routes for flags
  resources :flags, only: [:new, :create]


  #REST API RESOURCES
  namespace :api, defaults: { format: "json" } do
    resources :users, only: [:index, :show]

    resources :events, except: [:new, :edit] do
      resources :comments, except: [:new, :edit]
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord

  #Controlli sulle chiavi esterne
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :has_tags, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :child_flags, :class_name => "Flag", :foreign_key => "flaggedEvent_id", dependent: :destroy

  #Controlla che i seguenti campi non siano vuoti
  validates :where, presence: true
  validates :cords, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :title, presence: true
  validates :description, presence: true

  #Immagine di Copertina
  has_one_attached :cover

  #Controlla che le coordinate siano effettivamente valide
  validates_format_of :cords, with: /^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/, :multiline => true

  #Controlla che l'evento non finisca prima di cominciare
  def startBeforeEnd
    if start.to_datetime > self.end.to_datetime
      errors.add(:start, "Event ends before it starts")
    end
  end

  validate :startBeforeEnd

  #Controlla che la stringa di where corrisponda alle coordinate date
  def whereIsCords
    if self.where == ""
      errors.add(:where, "can't be empty")
    else
      here = RestClient.get "https://geocode.search.hereapi.com/v1/geocode", { params: { q: self.where, apiKey: ENV["HERE_API_KEY"] } }
      herejson = (JSON here.body)["items"]
      loc = self.coords
      loc[:lat] = loc[:lat].to_d
      loc[:lng] = loc[:lng].to_d

      for elem in herejson
        if (elem["position"]["lat"] == loc[:lat]) && (elem["position"]["lng"] == loc[:lng])
          return
        end
      end
      errors.add(:where, "Event coordinates do not match with the specified place")
    end
  end

  validate :whereIsCords

  #variabile indicante quanti utenti partecipano al dato evento
  def going
    Participation.where(event: self, value: "p").length
  end

  #variabile indicante quanti utenti sono interessati al dato evento
  def interested
    Participation.where(event: self, value: "i").length
  end

  #variabile indicante i nomi dei tag del dato evento
  def tags
    ht = HasTag.where(event: self)

    arr = []
    for elem in ht
      arr << Tag.find(elem.tag_id).name
    end

    return arr
  end

  #variabile indicante i commenti del dato evento (in ordine dentro una mappa)
  def comments
    commNoReply = Comment.where(event: self, previous_id: nil).sort_by(&:created_at)

    comments = []
    for elem in commNoReply
      comments << { comment: elem, replies: Comment.where(event: self, previous_id: elem.id).sort_by(&:created_at) }
    end

    return comments
  end

  #variabile indicante separatamente le coordinate di un evento
  def coords
    { lat: self.cords.split(",")[0], lng: self.cords.split(",")[1] }
  end

  #Per aggiungere una cover di default ad eventi sprovvisti
  def add_default_cover
    unless cover.attached?
      cover.attach(
        io: File.open(
          Rails.root.join(
            "app", "assets", "images", "default_cover.jpg"
          )
        ),
        filename: "default_cover.jpg",
        content_type: "image/jpg",
      )
    end
  end

  after_commit :add_default_cover, on: %i[create update]

  #Controlla che il formato della cover sia conforme
  def cover_format
    if cover.attached? && !cover.content_type.in?(%w(image/jpeg image/png))
      errors.add(:cover, "Image type is not supported try with jpeg or png")
    end
  end

  validate :cover_format

  #Overwrite json per le api
  def as_json(options = {})
    super(({ only: %i[id title description where cords start end tags], methods: %i[going interested tags] }).merge(options))
  end

  #Il valore dell'organizzatore per le api
  def organizer
    self.user.as_json
  end

end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  #GET su /api/events
  def index
    if params.has_key?(:apiKey) && !getUserBySK(params[:apiKey]).nil?
        @event = Event.all
        render json: @event.as_json(methods: %i[going interested organizer tags])
    else
      render body: nil, status: 401
    end
  end

  #GET su /api/events/:id
  def show
    if params.has_key?(:apiKey) && !getUserBySK(params[:apiKey]).nil?
      id = params[:id]

      if Event.exists?(id)
        @event = Event.find(id)
        render json: @event.as_json(methods: %i[going interested tags organizer comments])
      else
        render body: nil, status: 404
      end
    else
      render body: nil, status: 401
    end
  end

  #POST su /api/events
  def create
    current_user = getUserBySK(params[:apiKey])
    if !current_user.nil? && params.has_key?(:apiKey)
      if helpers.hasAll(params[:event])
        par = params[:event].permit(:where, :cords, :start, :end, :title,
          :description, :tags)

        tags = helpers.createTags(par[:tags])

        @event = Event.new(where: par[:where], cords: par[:cords], start: par[:start],
                            end: par[:end], title: par[:title], description: par[:description], user: current_user)

        if @event.valid?
          if @event.save
            helpers.createHasTags(tags, @event)
            render json: @event.as_json(methods: %i[going interested tags organizer comments])
          else
            render body: nil, status: 500
          end
        else
          render body: nil, status: 400
        end
      else
        render body: nil, status: 400
      end

      
    else
      render body: nil, status: 403
    end
  end

  #PUT o PATCH su /api/events/:id
  def update
    current_user = getUserBySK(params[:apiKey])
    if !current_user.nil? && params.has_key?(:apiKey)
      id = params[:id]

      if Event.exists?(id)
        @event = Event.find(id)

        if current_user.id == @event.user_id || current_user.admin

          if helpers.hasAll(params[:event])
            par = params[:event].permit(:where, :cords, :start, :end, :title,
              :description, :tags)

            @event.assign_attributes(where: par[:where], cords: par[:cords], start: par[:start],
              end: par[:end], title: par[:title], description: par[:description], modified: true)

            if @event.valid?
              if @event.save
                helpers.destroyHasTags(@event)
                tags = helpers.createTags(par[:tags])
                helpers.createHasTags(tags, @event)

                render json: @event.as_json(methods: %i[going interested tags organizer comments])
              else
                render body: nil, status: 500
              end
            else
              render body: nil, status: 400
            end
          else
            render body: nil, status: 400
          end
        else
          render body: nil, status: 403
        end
      else
        render body: nil, status: 404
      end
    else
      render body: nil, status: 401
    end
  end

  #DELETE su /api/events/:id
  def destroy
    current_user = getUserBySK(params[:apiKey])
    if !current_user.nil? && params.has_key?(:apiKey)
      id = params[:id]

      if Event.exists?(id)
        event = Event.find(id)

        if current_user.id == event.user_id || current_user.admin
          event.cover.purge_later

          if event.destroy
            render body: nil, status: 200
          else
            render body: nil, status: 500
          end
        else
          render body: nil, status: 403
        end
      else
        render body: nil, status: 404
      end
    else
      render body: nil, status: 401
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  #GET su /events/:id
  def show
    id = params[:id]

    if Event.exists?(id)
      @event = Event.find(id)
      if user_signed_in?
        # get its partecipation info
        @part = Participation.where(user_id: current_user.id, event_id: id)[0]
      end
    else
      render_404
    end
  end


  #GET su /events/new
  def new
    if !user_signed_in?
      render_401
    end
    @event = Event.new
  end


  #POST su /events
  def create
    if user_signed_in?
      par = params[:event].permit(:where, :cords, :start, :end, :title,
                                  :description, :cover, :tags)

      tags = helpers.createTags(par[:tags])

      @event = Event.new(where: par[:where], cords: par[:cords], start: par[:start],
                         end: par[:end], title: par[:title], description: par[:description],
                         cover: par[:cover], user: current_user)

      if @event.valid?
        if @event.save
          helpers.createHasTags(tags, @event)
          redirect_to event_path(@event)
        else
          render_500
        end
      else
        render :new
      end
    else
      render_401
    end
  end


  #GET su /events/:id/edit
  def edit
    if user_signed_in?
      id = params[:id]

      if Event.exists?(id)
        @event = Event.find(id)
        if !(current_user.id == @event.user_id || current_user.admin)
          render_403
        end
      else
        render_404
      end
    else
      render_401
    end
  end


  #PUT o PATCH su /events/:id
  def update
    if user_signed_in?
      id = params[:id]

      if Event.exists?(id)
        @event = Event.find(id)

        if current_user.id == @event.user_id || current_user.admin
          par = params[:event].permit(:where, :cords, :start, :end, :title,
                                      :description, :cover, :tags)

          if par[:cover].nil?
            @event.assign_attributes(where: par[:where], cords: par[:cords], start: par[:start],
                                     end: par[:end], title: par[:title], description: par[:description],
                                     modified: true)
          else
            @event.assign_attributes(where: par[:where], cords: par[:cords], start: par[:start],
                                     end: par[:end], title: par[:title], description: par[:description],
                                     cover: par[:cover], modified: true)
          end

          if @event.valid?
            if @event.save
              helpers.destroyHasTags(@event)
              tags = helpers.createTags(par[:tags])
              helpers.createHasTags(tags, @event)

              redirect_to event_path(@event)
            else
              render_500
            end
          else
            render :edit
          end
        else
          render_403
        end
      else
        render_404
      end
    else
      render_401
    end
  end


  #DELETE su /events/:id
  def destroy
    if user_signed_in?
      id = params[:id]

      if Event.exists?(id)
        event = Event.find(id)

        if current_user.id == event.user_id || current_user.admin
          event.cover.purge_later

          if event.destroy
            redirect_to root_path
          else
            render_500
          end
        else
          render_403
        end
      else
        render_404
      end
    else
      render_401
    end
  end
  
end

app/helpers/api/events_helper.rb
module Api::EventsHelper

    #Funzione usata per vedere che vengano passati tutti i parametri alla api per funzionare
    def hasAll(par)
        if (
            par[:title].present? &&
            par[:description].present? &&
            par[:start].present? &&
            par[:end].present? &&
            par[:where].present? &&
            par[:cords].present? &&
            (par[:tags].is_a? String)
        )
            return true
        else
            return false
        end
    end

end

app/helpers/events_helper.rb
module EventsHelper

    #Funzione usata per prendere la stringa dei tag, raccogliere quelli validi ed aggiungerli se già non esistono
    def createTags(t)
        tags = t.scan(/#\w+/).flatten.map(&:downcase).uniq
                
        for elem in tags
            tg = Tag.where(name: elem)[0]

            if tg.nil?   
                tg = Tag.new(name: elem)

                if tg.valid?
                    if ! tg.save
                        render_500
                    end
                else
                    render_400
                end
            end
        end

        return tags
    end


    #Funzione usata per creare il collegamento tra evento e tag se già non esiste
    def createHasTags(tags, event)                 
        for elem in tags
            tg = Tag.where(name: elem)[0]

            if tg.nil?   
                render_400
            else
                tg = HasTag.new(event_id: event.id, tag_id: tg.id)

                if tg.valid?
                    if ! tg.save
                        render_500
                    end
                else
                    render_400
                end
            end
        end
    end


    #Funzione usata per cancellare tutti i collegamenti tra evento e tag
    def destroyHasTags(event)
        has_tags = HasTag.where(:event_id => event.id)
        for elem in has_tags
            if !elem.destroy
                render_500
            end
        end
    end

end

app/views/events/edit.html.erb
<%= simple_form_for @event  do |f| %>
<div class="card" style="height:300px;overflow:hidden">
    <div id="cover" class="cover-bg-blur" style="background-image: url(<%=rails_blob_url( @event.cover) %>)"></div>
    <div id="cover-noblur" class="cover-bg" style="background-image: url(<%=rails_blob_url( @event.cover) %>)"></div>
</div>
<div class="row mt-3">

    <div class="col-sm-6">
        <%= f.input :cover %>
        <%= f.input :title, required:true %>
        <%= f.input :cords, as: :hidden %>
        <div class="row">
            <div class="col"> <%= f.input :start, as: :datetime, html5: true %> </div>
            <div class="col"> <%= f.input :end, as: :datetime, html5: true %> </div>
        </div>

        <%= f.input :where, input_html: {readonly: :true} %>

        <%= f.input :tags %>
    </div>

    <div class="col-sm-6">
        <div class="card mb-3" style="overflow:hidden">
            <div style="height: 325px" id="mapContainer" data-lat="<%= @event.coords[:lat] %>" data-lng="<%= @event.coords[:lng] %>"></div>
            <div class="card-body border-top form-inline">
                <input class="form-control w-100" id="mapSearchInput" placeholder="Search" aria-label="Search">
                <button type="button" class="btn btn-search" id="mapsearch">
                    <div class="search-icon"></div>
                </button>
            </div>
        </div>

    </div>
</div>
<%= f.input :description, required:true %>
<%= f.button :submit, class:"btn-primary btn-block" %>
<% end %>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#cover').css('background-image', 'url(' + e.target.result + ')');
                $('#cover-noblur').css('background-image', 'url(' + e.target.result + ')');
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }

    $("#event_cover").change(function() {
        readURL(this);
    });
</script>

app/views/events/new.html.erb
<%= simple_form_for @event  do |f| %>
<div class="card" style="height:300px;overflow:hidden;background-color:black">
    <div id="cover" class="cover-bg-blur"></div>
    <div id="cover-noblur" class="cover-bg"></div>
</div>
<div class="row mt-3">

    <div class="col-sm-6">

        <%= f.input :cover %>
        <%= f.input :title, required:true %>
        <%= f.input :cords, as: :hidden %>
        <div class="row">
            <div class="col"> <%= f.input :start, as: :datetime, html5: true %> </div>
            <div class="col"> <%= f.input :end, as: :datetime, html5: true %> </div>
        </div>

        <%= f.input :where, input_html: {readonly: :true} %>

        <%= f.input :tags %>
    </div>

    <div class="col-sm-6">
        <div class="card mb-3" style="overflow:hidden">
            <div style="height: 325px" id="mapContainer"></div>
            <div class="card-body border-top form-inline">
                <input class="form-control w-100" id="mapSearchInput" placeholder="Search" aria-label="Search">
                <button type="button" class="btn btn-search" id="mapsearch">
                    <div class="search-icon"></div>
                </button>
            </div>
        </div>

    </div>
</div>
<%= f.input :description, required:true %>
<%= f.button :submit, class:"btn-primary btn-block" %>
<% end %>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#cover').css('background-image', 'url(' + e.target.result + ')');
                $('#cover-noblur').css('background-image', 'url(' + e.target.result + ')');
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }

    $("#event_cover").change(function() {
        readURL(this);
    });
</script>

app/views/events/show.html.erb
<div class="card card-event">
    <div id="cover" class="cover-bg-blur" style="background-image: url(<%=rails_blob_url( @event.cover) %>)"></div>
    <div id="cover-noblur" class="cover-bg" style="background-image: url(<%=rails_blob_url( @event.cover) %>)"></div>
    <div class="card-body">
        <div class="d-flex flex-wrap">
            <div>
                <h4 class="m-0"><%= @event.title %></h4>
                <%= link_to @event.user.username, user_path(@event.user) %>
                <% if @event.user.verification || @event.user.admin %>
                <div class="<%= @event.user.verificationIcon %>"></div>
                <% end %>
                <br>
                <%= @event.start.strftime("%e %B %Y, %H:%M") %> - <%= @event.end.strftime("%e %B %Y, %H:%M")%>
            </div>
            <div class="ml-auto">
                <div class="text-right mb-2">
                    <span class="mr-2"><strong><%= @event.interested %></strong> Interested </span>
                    ·
                    <strong><%= @event.going %></strong> Going </div>
                <% if user_signed_in? %>
                <div>
                    <% if current_user != @event.user %>
                    <button class="btn btn-danger" onclick="flag('event','<%= @event.id %>')">
                        <div class="flag-icon"></div>
                    </button>

                    <%if @part.nil? %>
                    <%= button_to( event_participations_path(@event), params: { participation: { value: "i" } },
                                        method: :post, form_class: "d-inline-block", class:"btn btn-primary" ) do %>
                    <div class="interested-icon"></div> Interested
                    <% end %>
                    <%= button_to( event_participations_path(@event), params: { participation: { value: "p" } }, 
                                        method: :post, form_class: "d-inline-block", class:"btn btn-success" ) do %>

                    <div class="going-icon"></div> Going
                    <% end %>
                    <% elsif @part.value == 'i' %>
                    <%= link_to( event_participation_path(@event, @part), method: :delete , class:"btn btn-warning" ) do %>
                    <div class="not-interested-icon"></div> Not interested
                    <% end %>
                    <%= button_to( event_participation_path(@event, @part), params: { participation: { value: "p" } }, 
                                            method: :put, form_class: "d-inline-block", class:"btn btn-success" ) do %>
                    <div class="going-icon"></div> Going
                    <% end %>
                    <% else %>
                    <%= button_to( event_participation_path(@event, @part), params: { participation: { value: "i" } }, 
                                            method: :put, form_class: "d-inline-block", class:"btn btn-primary" ) do %>
                    <div class="interested-icon"></div> Interested
                    <% end %>
                    <%= link_to( event_participation_path(@event, @part), method: :delete , class:"btn btn-warning" ) do %>
                    <div class="not-going-icon"></div> Not Going
                    <% end %>
                    <% end %>
                    <% else %>
                    <%= link_to( edit_event_path(@event), class: "btn btn-warning") do%>
                    <div class="modify-icon"></div> Modify
                    <% end %>
                    <%= link_to( event_path(@event), data:{ confirm: "Are you sure? "}, class: "btn btn-danger", method: :delete) do%>
                    <div class="delete-icon"></div> Delete
                    <% end %>
                    <% end %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<br>
<div class="card">
    <div class="card-body">
        <div class="d-flex">
            <h6 class="card-title mr-auto"> Description </h6>
            <% if @event.modified? %>
            <div class='text-muted'> modified </div>
            <% end %>
        </div>
        <%= @event.description %><br>
        <br>
        <h6 class="card-title"> Tags </h6>
        <div class="text-primary">
            <% @event.tags.each do |t| %>
            <%= link_to(search_path(q: "#{t}")) do%>
            <%= t %>
            <% end %>
            <%end%>
        </div>
    </div>
</div>
<br>

<div class="card-deck">
    <div class="card" style="overflow:hidden">
        <div style="height: 300px" id="mapContainer" data-lat="<%= @event.coords[:lat] %>" data-lng="<%= @event.coords[:lng] %>"></div>
        <div class="card-body d-flex border-top">
            <div id="mapEventInfo"><%= @event.where %></div>
            <a class="ml-auto btn btn-primary d-flex" href="https://share.here.com/l/<%= "#{@event.coords[:lat]},#{@event.coords[:lng]}" %>?z=13&t=traffic&p=yes" style=" border-radius: 100px; min-height: 62px; min-width: 62px;">
                <div class="directions-icon" style="--icon-size: 36px; margin: auto;"> </div>
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
        <% if user_signed_in? %>
            <%= form_with model: Comment.new, url: event_comments_path(@event), class: "form-inline flex-nowrap", local: true do |f| %>
            <%= f.text_field :content, class: "form-control flex-grow-1 w-100", placeholder: "Write a comment", autocomplete: "off" %>
            <%= button_tag(type: 'submit', class: "ml-3 btn btn-primary", id: "comment_submit") do %>
            <div class="send-comment-icon"></div>
            <% end %>
            <% end %>
        <% else %>
            <span class="text-muted">
                You are not logged in, please <%= link_to  "Log In", new_user_session_path %> or <%= link_to  "Register", new_user_registration_path %> to comment
            </span>
        <% end %>
        </div>
        <div class="card-body comments-container">

            <% @event.comments.each do |c| %>
            <div class="mb-3">
                <div class="media" id="comment<%= c[:comment].id %>">
                    <%= image_tag c[:comment].user.avatar_thumbnail, class:"avatar align-self-center comments-avatar mr-3" %>
                    <div class="media-body comment">
                        <div class="d-flex">
                            <%= link_to(user_path(c[:comment].user)) do%>
                            <strong class="mr-auto"> <%= c[:comment].user.username %>
                            <div class="<%= c[:comment].user.verificationIcon %>"></div>
                            </strong>
                            <% end %>
                            <% if c[:comment].isModified? %>
                            <span class="ml-auto text-muted"> Modified </span>
                            <% end %>
                        </div>
                        <%= c[:comment].content %>
                    </div>
                </div>
                <div class="replies">
                    <% if user_signed_in? %>
                    <a data-toggle="collapse" href="#replyForm<%= c[:comment].id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
                        reply
                    </a>
                    <% if current_user == c[:comment].user %>
                    ·
                    <a class="text-warning" data-toggle="collapse" href="#modifyForm<%= c[:comment].id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
                        modify
                    </a> ·
                    <%= link_to "delete", event_comment_path(@event, c[:comment]), data: { confirm: "Are you sure?" }, method: :delete , class:"text-danger" %>
                    <div class="collapse" id="modifyForm<%= c[:comment].id %>">
                        <%= form_with model: c[:comment], url: event_comment_path(@event,c[:comment]), method: "patch", class: "form-inline flex-nowrap mb-3", local: true do |f| %>
                        <%= f.text_field :content, class: "form-control flex-grow-1 w-100", autocomplete: "off" %>
                        <%= button_tag(type: 'submit', class: "ml-3 btn btn-warning") do %>
                        <div class="modify-icon"></div>
                        <% end %>
                        <% end %>
                    </div>
                    <% else %>
                    ·
                    <a class="text-danger" style="cursor: pointer;" onclick="flag('comment','<%= c[:comment].id %>')">
                        flag
                    </a>
                    <% end %>
                    <% end %>
                    <% c[:replies].each do |r| %>
                    <div class="my-2">
                        <div class="media" id="comment<%= r.id %>">
                            <%= image_tag r.user.avatar_thumbnail, class:"avatar align-self-center comments-avatar mr-3" %>
                            <div class="media-body comment">
                                <div class="d-flex">
                                    <%= link_to(user_path(r.user)) do%>
                                    <strong class="mr-auto"> <%= r.user.username %>
                                    <div class="<%= r.user.verificationIcon %>"></div>
                                    </strong>
                                    <% end %>
                                    <% if r.isModified? %>
                                    <span class="ml-auto text-muted"> Modified </span>
                                    <% end %>
                                </div>
                                <%= r.content %>
                            </div>
                        </div>
                        <div class="replies">
                            <%if user_signed_in? %>
                            <% if current_user == r.user %>
                            <a class="text-warning" data-toggle="collapse" href="#modifyForm<%= r.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
                                modify
                            </a> ·
                            <%= link_to "delete", event_comment_path(@event, r), data: { confirm: "Are you sure?" }, method: :delete , class:"text-danger" %>
                            <div class="collapse" id="modifyForm<%= r.id %>">
                                <%= form_with model: r, url: event_comment_path(@event,r), method: "patch", class: "form-inline flex-nowrap mb-3", local: true do |f| %>
                                <%= f.text_field :content, class: "form-control flex-grow-1 w-100", autocomplete: "off" %>
                                <%= button_tag(type: 'submit', class: "ml-3 btn btn-warning") do %>
                                <div class="modify-icon"></div>
                                <% end %>
                                <% end %>
                            </div>
                            <% else %>
                            ·
                            <a class="text-danger" style="cursor: pointer;"  onclick="flag('comment','<%= r.id %>')">
                                flag
                            </a>
                            <% end %>
                            <% end %>
                        </div>
                    </div>
                    <%end%>
                    <%if user_signed_in? %>
                    <div class="collapse" id="replyForm<%= c[:comment].id %>">
                        <%= form_with model: Comment.new, url: event_comments_path(@event), class: "form-inline flex-nowrap mb-3", local: true do |f| %>
                        <%= f.hidden_field :previous_id, :value => c[:comment].id %>
                        <%= f.text_field :content, class: "form-control flex-grow-1 w-100", placeholder: "Write a comment", autocomplete: "off" %>
                        <%= button_tag(type: 'submit', class: "ml-3 btn btn-primary") do %>
                        <div class="send-reply-icon"></div>
                        <% end %>
                        <% end %>
                    </div>
                    <%end%>
                </div>
            </div>
            <%end%>

            <% if @event.comments.empty? %>
            <span class="text-muted"> This event has no comments yet </span>
            <% end %>
        </div>
    </div>
</div>