config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost:3000"


  #Routes linked to users
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :follows, except: [:show, :new, :edit, :update]
  end


  #Routes for tags (follows tag)
  resources :tags, except: [:index, :show, :new, :edit, :update]


  #Routes for the pages (home, search, about us, contact us)
  root to: "pages#home"
  get "/search", to: "pages#search", as: "search"
  get "/about-us", to: "pages#aboutus", as: "aboutus"


  #Routes for events (and comments, and participations)
  resources :events, except: [:index] do
    resources :comments, except: [:index, :show, :new, :edit]
    resources :participations, except: [:index, :show, :new, :edit]
  end


  #Routes for chats (and messages)
  resources :chats, except: [:new, :edit, :update, :destroy] do
    resources :messages, only: [:create]
  end


  #Routes for flags
  resources :flags, only: [:new, :create]


  #REST API RESOURCES
  namespace :api, defaults: { format: "json" } do
    resources :users, only: [:index, :show]

    resources :events, except: [:new, :edit] do
      resources :comments, except: [:new, :edit]
    end
  end

end

app/views/pages/_filters.html.erb
<div class="d-flex">
    <a class="ml-auto mr-2" data-toggle="collapse" href="#filterscollapse" role="button" aria-expanded="false" aria-controls="collapseExample">
        Filters
    </a>
</div>
<div class="collapse mb-3" id="filterscollapse">
    <div class="card">
        <div class="card-body">
            <div class="d-flex flex-wrap flex-sm-row flex-column">
                <div class="col-sm-6">
                    <input class="form-control" id="cords" hidden>
                    <div class="form-group">
                        <label for="searchPlaces">Search Places</label>
                        <div class="form-inline">
                            <input class="form-control w-100" id="searchPlacesInput" placeholder="Search" aria-label="Search">
                            <button type="button" class="btn btn-search" id="searchPlaces" onclick="searchPlaces()">
                                <div class="search-icon"></div>
                            </button>
                            <div class="invalid-feedback">
                                Search field can't be empty.
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="selectSpecificPlace">Select Place</label>
                        <select class="form-control" id="selectSpecificPlace" aria-describedby="selectPlace">
                            <% if @p.present? %>
                                <option data-cords="<%= @w %>"><%= @p %></option>
                            <% end %>
                        </select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="startDate">Starting Date</label>
                        <input class="form-control" type="date" id="startDate" aria-describedby="startDate" value="<%= @es %>">
                        <div class="invalid-feedback">
                            invalid date.
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="endingDate">Ending Date</label>
                        <input class="form-control" type="date" id="endingDate" aria-describedby="endDate" value="<%= @ee %>">
                        <div class="invalid-feedback">
                            invalid date.
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="d-flex">
                        <button class="ml-auto btn btn-danger" onclick="clearFilters()"> Clear filters </button>
                        <button class="ml-4 btn btn-primary" onclick="addFilters()"> Add filters </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
<%= javascript_include_tag "filters" %>

app/views/pages/aboutus.html.erb
<img class="card w-100" src="<%= image_path("logowbg.png") %>">

<div class="card my-4">
    <div class="card-body">
        <h5 class="card-title"> About Us </h5>
        <p>Acara is a passion project from a fervent group of students!</p>
        <p>Acara allows to search for, create, participate and comment on events from all over the world, connecting people like never before!</p>
        <p>Make new friends throught our chats, feed your interestes with our events and find new experiences of a lifetime!</p>
    </div>
</div>

<div class="card my-4">
    <div class="card-body">
        <h5 class="card-title"> Meet our Team </h5>
        <div class="d-flex flex-wrap flex-sm-row flex-column">
            <div class="my-2 col">
                <div class="card">
                    <img src="https://avatars1.githubusercontent.com/u/35846576?s=460&u=b30d42dde33696c7fd5d81c71dcf44faaba028b0&v=4" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title"> Juan Sebastian Arboleda </h5>
                        UI and Security
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-block btn-primary" href="https://github.com/AlZeck">
                            <div class="git-icon"></div>
                            Github
                        </a>
                    </div>
                </div>
            </div>
            <div class="my-2 col">
                <div class="card">
                    <img src="https://avatars3.githubusercontent.com/u/61871077?s=400&v=4" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title"> Andrea Cerone </h5>
                        API and Testing
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-block btn-primary" href="https://github.com/andrea-cerone">
                            <div class="git-icon"></div>
                            Github
                        </a>
                    </div>
                </div>
            </div>
            <div class="my-2 col">
                <div class="card">
                    <img class="card-img-top" src="https://avatars3.githubusercontent.com/u/61872024?s=460&amp;u=759cfb8ac9427deb94f9b3547373ab84778547a3&amp;v=4">
                    <div class="card-body">
                        <h5 class="card-title"> Matteo Di Stadio </h5>
                        Models and Controllers
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-block btn-primary" href="https://github.com/matteo-ds">
                            <div class="git-icon"></div>
                            Github
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card" id="contact-us">
    <div class="card-body">
        <h5 class="card-title"> Contact Us </h5>
        You can <a href="mailto:team@acara.com">send us an email</a> or, if you're logged in, you can contact us throught direct messages to our admin's accounts: 
        <div class="d-flex flex-wrap justify-content-center">
            <% @admins.each do |user| %>
                <%= link_to user_path(user) do %>
                <div class="card mx-3 my-3" style="max-width:150px;min-width:150px;">
                    <div class="card-body" style="text-align: center;">
                    <%= image_tag user.avatar_thumbnail, class:"avatar mb-3" %><br>
                    <%= user.username %>
                    <div class="<%= user.verificationIcon %>" style="vertical-align: middle;"></div>
                    </div>
                </div>
                <% end %>
            <% end %>
        </div>
        <% if @admins.empty? %>
        <span class="text-muted"> OPS, it looks like there's no available admin account at the moment </span>
        <%end%>
    </div>
</div>

app/views/pages/home.html.erb
<% if !@hasGL %> <%= javascript_include_tag "getGL" %> <% end %>

<img class="card w-100 mb-3" src="<%= image_path("logowbg.png") %>">

<div class="card">
    <div class="card-body">
        <h3 class="card-title">Events</h3>
        <div class="d-flex flex-wrap flex-md-row flex-column">
            <% @events.each do |event| %>
            <div class="col-md-6 my-3">
            <div class="card card-event hover-info" style="min-height: 270px; height:30vh">
                <div id="cover" class="cover-bg-blur" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                <div id="cover-noblur" class="cover-bg" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                <div class="card-body">
                    <%= link_to( event_path(event) ) do %>
                    <%= event.title %>
                    <%end%>
                    <div class="extra-info">
                        <%= event.start.strftime("%e %B %Y, %H:%M") %> - <%= event.end.strftime("%e %B %Y, %H:%M")%> <br>
                        <%= event.where %>
                    </div>
                </div>
            </div>
            </div>
            <% end %>
        </div>
        <% if @events.empty? %>
        <span class="text-muted"> There are no events found </span>
        <%end%>
    </div>
</div>

app/views/pages/search.html.erb
<% if !@hasGL %> <%= javascript_include_tag "getGL" %> <% end %>


<% if @risposta[:type] == "events" %>
    <%= render partial: 'filters' %>
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Events</h3>
            <div class="d-flex flex-wrap flex-md-row flex-column">
                <% @risposta[:content].each do |event| %>
                <div class="col-md-6 my-3">
                    <div class="card card-event hover-info" style="min-height: 270px; height:30vh">
                        <div id="cover" class="cover-bg-blur" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                        <div id="cover-noblur" class="cover-bg" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                        <div class="card-body">
                            <%= link_to( event_path(event) ) do %>
                            <%= event.title %>
                            <%end%>
                            <div class="extra-info">
                                <%= event.start.strftime("%e %B %Y, %H:%M") %> - <%= event.end.strftime("%e %B %Y, %H:%M")%> <br>
                                <%= event.where %>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
            <% if @risposta[:content].empty? %>
            <span class="text-muted"> There are no events found </span>
            <%end%>
        </div>
    </div>
<% elsif @risposta[:type] == "users" %>
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Users</h3>
            <div class="d-flex flex-wrap justify-content-center">
                <% @risposta[:content].each do |user| %>
                    <%= link_to user_path(user) do %>
                    <div class="card mx-3 mb-3" style="max-width:150px;min-width:150px;">
                        <div class="card-body" style="text-align: center;">
                        <%= image_tag user.avatar_thumbnail, class:"avatar mb-3" %><br>
                        <%= user.username %>
                        <div class="<%= user.verificationIcon %>" style="vertical-align: middle;"></div>
                        </div>
                    </div>
                    <% end %>
                <% end %>
            </div>
            <% if @risposta[:content].empty? %>
            <span class="text-muted"> There are no users found </span>
            <%end%>
        </div>
    </div>
<% else %>
    <div class="card mb-3">
        <div class="card-body">
            <h3 class="card-title">Similar Tags</h3>
            <div class="d-flex flex-wrap flex-sm-row flex-column">
            <% @risposta[:content][:tags].each do |tag| %>
                <div class="d-flex p-3 col-sm-6 align-items-center">
                    <%= link_to(search_path(q: "#{tag.name}")) do%>
                        <%= tag.name %>
                    <% end %>
                    <% if user_signed_in? %>
                        <% if !current_user.followsTag?(tag) %>
                            <%= button_to( tags_path, params: { follows_tag: { tag_id: tag.id } }, 
                                method: :post, form_class: "d-inline-block ml-auto", class: "btn btn-primary" ) do %>
                                Follow
                            <% end %>
                        <% else %>
                            <%= button_to( tag_path(FollowsTag.where(user: current_user, tag: tag)[0]), method: :delete, form_class: "d-inline-block ml-auto", 
                                            class:"btn btn-danger" ) do %>
                                Unfollow
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
            <% end %>
            </div>
            <% if @risposta[:content][:tags].empty? %>
            <span class="text-muted"> There are no similar tags found </span>
            <%end%>
        </div>
    </div>
    <%= render partial: 'filters' %>
    <div class="card">
        <div class="card-body">
            <h3 class="card-title"> Events </h3>
            <div class="d-flex flex-wrap flex-md-row flex-column">
                <% @risposta[:content][:events].each do |event| %>
                <div class="col-md-6 my-3">
                    <div class="card card-event hover-info" style="min-height: 270px; height:30vh">
                        <div id="cover" class="cover-bg-blur" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                        <div id="cover-noblur" class="cover-bg" style="background-image: url(<%=rails_blob_url( event.cover) %>)"></div>
                        <div class="card-body">
                            <%= link_to( event_path(event) ) do %>
                            <%= event.title %>
                            <%end%>
                            <div class="extra-info">
                                <%= event.start.strftime("%e %B %Y, %H:%M") %> - <%= event.end.strftime("%e %B %Y, %H:%M")%> <br>
                                <%= event.where %>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
            <% if @risposta[:content][:events].empty? %>
            <span class="text-muted"> There are no events found </span>
            <%end%>
        </div>
    </div>
<% end %>