config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost:3000"


  #Routes linked to users
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :follows, except: [:show, :new, :edit, :update]
  end


  #Routes for tags (follows tag)
  resources :tags, except: [:index, :show, :new, :edit, :update]


  #Routes for the pages (home, search, about us, contact us)
  root to: "pages#home"
  get "/search", to: "pages#search", as: "search"
  get "/about-us", to: "pages#aboutus", as: "aboutus"


  #Routes for events (and comments, and participations)
  resources :events, except: [:index] do
    resources :comments, except: [:index, :show, :new, :edit]
    resources :participations, except: [:index, :show, :new, :edit]
  end


  #Routes for chats (and messages)
  resources :chats, except: [:new, :edit, :update, :destroy] do
    resources :messages, only: [:create]
  end


  #Routes for flags
  resources :flags, only: [:new, :create]


  #REST API RESOURCES
  namespace :api, defaults: { format: "json" } do
    resources :users, only: [:index, :show]

    resources :events, except: [:new, :edit] do
      resources :comments, except: [:new, :edit]
    end
  end

end

app/views/layouts/_alerts.html.erb
<% if notice.present? %>
<div class="alert alert-primary <%= "mb-0" if !has_navbar %>" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color: #000">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>
<% if alert.present? %>
<div class="alert alert-warning <%= "mb-0" if !has_navbar %>" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color: #000">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<div class="sticky-bottom footer">
    <div class="pt-2 pb-2 container">
        <div class="d-flex flex-wrap-reverse">
            <div class="text-muted">
                Copyright © 2020 Acara Italy. All rights reserved
            </div>
            <div class="ml-auto">
                <%= link_to  "About Us", aboutus_path %>
                <%= link_to  "Contact Acara", aboutus_path(anchor: "contact-us") ,  class: "ml-4" %>
            </div>
        </div>
    </div>
</div>
</footer>

app/views/layouts/_modals.html.erb
<div class="modal fade" id="modalComm" tabindex="-1" role="dialog" aria-labelledby="modalCommLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">

        
        <!--Content-->
        <div class="modal-content" style="height:500px">

            <!--Body-->
            <div id="modalComm-body" class="modal-body mb-0 p-0"></div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="/">
            <%= image_tag("/logo.png", size: "70x40", alt: "Homepage") %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="form-inline w-75 mx-auto my-2 my-lg-0" action="<%= search_path %>" method="get">
                <input name="q" class="form-control w-100 navbar-search" placeholder="Search for Event, @User or #Tag" aria-label="Search">
                <button class="btn btn-search" type="submit"><div class="search-icon"></div></button>
            </form>

            <ul class="navbar-nav">
                <% if current_user %>
                <li class="nav-item active mr-2">
                    <%= link_to( new_event_path, class: "nav-link") do%>
                    <div class="new-event-icon"></div>
                    <% end %>
                </li>
                <li class="nav-item dropdown mr-2">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= image_tag current_user.avatar_thumbnail, class:"avatar navbar-avatar" %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <%= link_to 'My Profile', user_path(current_user), class: "dropdown-item"%>
                        <%= link_to 'Chats', chats_path, class: "dropdown-item"%>
                        <% if current_user.admin? %>
                        <%= link_to 'Dashboard', Trestle.config.path , class: "dropdown-item"%>
                        <% end %>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item"%>
                        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "dropdown-item"%>
                    </div>
                </li>
                <% else %>
                <li class="nav-item active">
                    <%= link_to 'Log In', new_user_session_path, class: "nav-link"%>
                </li>
                <li class="nav-item active">
                    <%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>
                </li>
                <% end %>
                <li class="nav-item active">
                    <button class="btn nav-link" id="themeUpdater" onclick="return updateColor();">
                        <div class="lightbulb-icon"> </div>
                    </button>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Acara</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application'%>
</head>

<body>
    <%= javascript_include_tag "dark-mode" %>
    <%= render('layouts/navbar') if has_navbar %>
    <%= render('layouts/modals') %>
    <!--   <%= render 'layouts/alerts'%> -->
    <div id="pageContent" class="<%= 'container container-body py-4' if has_navbar %>">
        <%= render('layouts/alerts') %>
        <%= yield %>
    </div>
    <%= render('layouts/footer') if has_navbar %>
    <%= javascript_include_tag "newflag" %>
    <%= javascript_include_tag "modal-comms" %>
    <% if has_maps %>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js"></script>
    <link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
    <%= javascript_include_tag "maps" %>
    <% end %>
</body>

</html>